### ISSUE TITLE
Implement Typescript for the Project

### ISSUE THREAD

**Issue by sebherrerabe** [HackYourFutureBelgium/hackyourfuture.be#261]
### Description

Currently, the project is built using Gatsby as the framework, but we have not yet implemented Typescript. I'd like to propose to start applying Typescript for upcoming features and eventually refactor the legacy code.

### Objective

The objective of this issue is to add Typescript to the project and configure the necessary tooling to support it.

### Tasks
- [ ] Configure linting and formatting tools for Typescript
- [ ] Install `@types/node`, `@types/react`, `@types/react-dom`, and `typescript` as devDependencies.
- [ ] Add a `tsconfig.json` file using `npx tsc --init` or use the one from `gatsby-minimal-starter-ts`.
- [ ] Run `gatsby clean` to remove any old artifacts.
- [ ] Rename your `gatsby-*` files:
     - `gatsby-node.js` to `gatsby-node.ts`
     - `gatsby-config.js` to `gatsby-config.ts`
     - `gatsby-browser.js` to `gatsby-browser.tsx`
     - `gatsby-ssr.js` to `gatsby-ssr.tsx`
- [ ] Address any of the current limitations and test the behavior.
- [ ] Document the Typescript implementation in the project's README.md file

### Outcome

The project will have Typescript implemented, which will help to catch potential errors earlier in the development process and provide better type safety for the codebase. This will also make it easier to maintain and scale the project in the future.

### Additional Information

- We will use the strict mode configuration for Typescript.
- The conversion process will happen gradually, starting with new files for upcoming features.
- Any existing code that is not converted to Typescript will continue to work as it currently does.
- Once Typescript is fully implemented, we will evaluate the possibility of refactoring the legacy code to Typescript.

**Comment by KevinTss** [comment]
Good initiative @sebherrerabe I just started a PR about it.
I'll continue on that when I go some time. Feel free to give a hand if you feel 🚀 
Thanks for this
