### ISSUE TITLE
Build Design System base

### ISSUE THREAD

**Issue by KevinTss** [HackYourFutureBelgium/hackyourfuture.be#265]
# Context

We want to build a basic Design System, more precisely, the UI kit which will reflect the branding through web components who will be used on the website.

# Solution

We will use [Storybook](https://storybook.js.org/) for this. We can consider that as a tool to materialise the UI elements, plus they do have experience on [design system](https://storybook.js.org/tutorials/design-systems-for-developers/) use case which will help us.

# Concretely

We will build a components based library which are Styled components (Not plain react component)

# Inventory component to build

- [ ] [Button](https://github.com/HackYourFutureBelgium/hackyourfuture.be/issues/264) (as styled)
- [ ] [Heading](https://github.com/HackYourFutureBelgium/hackyourfuture.be/issues/266) (as styled)
- [ ] [Paragraph](https://github.com/HackYourFutureBelgium/hackyourfuture.be/issues/267) (as styled)
- [ ] [Image](https://github.com/HackYourFutureBelgium/hackyourfuture.be/issues/268) (as styled)
- [ ] [Input](https://github.com/HackYourFutureBelgium/hackyourfuture.be/issues/269) (as styled)

**Comment by sebherrerabe** [comment]
Good idea to have a look to this videos for implementation: https://www.youtube.com/watch?v=qSkHRVLcj6U
