### ISSUE TITLE
Component- Input

### ISSUE THREAD

**Issue by KevinTss** [HackYourFutureBelgium/hackyourfuture.be#269]
### Description
We need to create a reusable input component that can be used in various forms across our application. This component should have customizable styles and be able to handle user input, validation, and feedback.

### Task List
- [ ] Create the Input component with the following features:
    - [ ] Accepts props for placeholder, label, value, error message, and input type
    - [ ] Provides validation feedback to the user when necessary
- [ ] Create a Storybook story for the Input component
    - [ ] Include multiple examples of the component being used with different props
    - [ ] Show how the component responds to user input and validation feedback
- [ ] Ensure that the component is accessible to users with disabilities
- [ ] Style the component based on the attached Figma design

### Figma Design Preview

![Image](https://user-images.githubusercontent.com/96073676/226203849-f41eba6f-19ec-44cf-9116-ab86bb2f38a5.png)

### Acceptance Criteria
- The Input component should be reusable and able to handle different types of input and validation feedback
- The Storybook story should demonstrate the component's features and show examples of it being used with different props
- The component should be accessible to users with disabilities
- The component should match the design in the attached Figma preview.
